[package]
name = "SmartInscription"
authors = ["Pika", "10xhunter", "jolestar", "jojoo-eth"]
version = "4.1.7"
#mainnet
published-at = "0xb3e7870f4f145a55c698a90e625551c743b6bac04486306ef3ed372c1e180dfc"
#testnet
#published-at = "0x1258e7b1a145ed6cf91d17d4fd034a27458135df3eed6ac3dfa7158864a8ae35"
#devnet
#published-at = "0x3579bb6bf94eddd21e05bfeb16eb28f8e2d2c79561745fffab671b6bff6ea2f6"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.17.3", override = true}
#CetusClmm = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/clmmpool", rev = "testnet-v1.2.0" }
CetusClmm = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/clmmpool", rev = "mainnet-v1.2.0" }
#IntegerMate = { git = "https://github.com/CetusProtocol/integer-mate.git", subdir = "sui", rev = "sui-testnet" }
IntegerMate = { git = "https://github.com/CetusProtocol/integer-mate.git", subdir = "sui", rev = "sui-v1.1.0" }

[addresses]
#mainnet
smartinscription = "0x830fe26674dc638af7c3d84030e2575f44a2bdc1baa1f4757cfe010a4b106b6a"
#testnet
# smartinscription = "0x757a3250eaaa0ab7f2873f70e496688e35b27928a2d4a31bec996a9f35ba8686"
#smartinscription = "0x0"
