[package]
name = "SmartInscription"
authors = ["Pika", "10xhunter", "jolestar", "jojoo-eth"]
version = "4.1.1"
#mainnet
#published-at = "0xbaaa200e83ceae97f45251297c8870be5d00fb392f0bc7a5716bdf95e75f3c92"
#testnet
published-at = "0x58d8621fb9b6b20f476ffc862c2c37e8d759cb4511f0997acc780d39ad27ccc6"
#devnet
#published-at = "0x3579bb6bf94eddd21e05bfeb16eb28f8e2d2c79561745fffab671b6bff6ea2f6"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.17.3", override = true}
CetusClmm = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/clmmpool", rev = "testnet-v1.2.0" }
IntegerMate = { git = "https://github.com/CetusProtocol/integer-mate.git", subdir = "sui", rev = "sui-testnet" }

[addresses]
#mainnet
#smartinscription = "0x830fe26674dc638af7c3d84030e2575f44a2bdc1baa1f4757cfe010a4b106b6a"
#testnet
smartinscription = "0x757a3250eaaa0ab7f2873f70e496688e35b27928a2d4a31bec996a9f35ba8686"
#smartinscription = "0x0"
