[package]
name = "SmartInscription"
authors = ["Pika", "10xhunter", "jolestar", "jojoo-eth"]
version = "0.0.1"
published-at = "0xebbba763f5fc01d90c2791c03536a373791b634600e81d4e08b85f275f1274fa"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

[addresses]
smartinscription = "0x0"
